version: "3.8"
services:
  web:
    build: .
    depends_on:
      - redis
#    volumes:
#      - .:/usr/src/app/
#    environment:
#      FLASK_ENV: development
  redis:
    image: "redis:alpine"